import { CarCardData } from "@/Types/Booking/CarBooking.types";

// ===============================Sample Car Data==============================
/**
 * Comprehensive sample car rental data for demonstration
 * Includes various car types, prices, and features
 */
export const SAMPLE_CARS: CarCardData[] = [
  {
    id: "1",
    name: "Nissan Qashqai or similar",
    carType: "Standard",
    image:
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop",
    transmission: "Automatic",
    seats: 5,
    luggage: 2,
    features: [
      { id: "1", name: "Unlimited mileage", icon: "unlimited" },
      { id: "2", name: "Free cancellation", icon: "cancel" },
      { id: "3", name: "Basic Collision Damage Protection", icon: "shield" },
      { id: "4", name: "Pay now and save", icon: "save" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.5,
    reviewCount: 234,
    pricePerDay: 22,
    totalPrice: 66,
    currency: "$",
    company: "Nissan Qashqai or similar",
    companyLogo: "https://via.placeholder.com/80x80/10B981/FFFFFF?text=NISSAN",
    isAvailable: true,
  },
  {
    id: "2",
    name: "Mazda MX30 or similar",
    carType: "Standard",
    image:
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&h=600&fit=crop",
    transmission: "Automatic",
    seats: 5,
    luggage: 2,
    features: [
      { id: "1", name: "Unlimited mileage", icon: "unlimited" },
      { id: "2", name: "Free cancellation", icon: "cancel" },
      { id: "3", name: "Basic Collision Damage Protection", icon: "shield" },
      { id: "4", name: "Online check-in", icon: "online" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.7,
    reviewCount: 189,
    pricePerDay: 27,
    totalPrice: 81,
    currency: "$",
    company: "Mazda MX30 or similar",
    companyLogo: "https://via.placeholder.com/80x80/CC0000/FFFFFF?text=MAZDA",
    isAvailable: true,
  },
  {
    id: "3",
    name: "Nissan Qashqai or similar",
    carType: "SUV",
    image:
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop",
    transmission: "Manual",
    seats: 5,
    luggage: 2,
    features: [
      { id: "1", name: "Unlimited mileage", icon: "unlimited" },
      { id: "2", name: "Free cancellation", icon: "cancel" },
      { id: "3", name: "Basic Collision Damage Protection", icon: "shield" },
      { id: "4", name: "Online check-in", icon: "online" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.3,
    reviewCount: 156,
    pricePerDay: 13.33,
    totalPrice: 40,
    currency: "$",
    company: "Nissan Qashqai or similar",
    companyLogo: "https://via.placeholder.com/80x80/10B981/FFFFFF?text=NISSAN",
    isAvailable: true,
  },
  {
    id: "4",
    name: "Toyota Corolla or similar",
    carType: "Compact",
    image:
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&h=600&fit=crop",
    transmission: "Automatic",
    seats: 5,
    luggage: 2,
    features: [
      { id: "1", name: "Unlimited mileage", icon: "unlimited" },
      { id: "2", name: "Free cancellation", icon: "cancel" },
      { id: "3", name: "Basic Collision Damage Protection", icon: "shield" },
      { id: "4", name: "Pay now and save", icon: "save" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.6,
    reviewCount: 312,
    pricePerDay: 11.67,
    totalPrice: 35,
    currency: "$",
    company: "Compact",
    companyLogo: "https://via.placeholder.com/80x80/0066B2/FFFFFF?text=TOYOTA",
    isAvailable: true,
  },
  {
    id: "5",
    name: "Toyota Corolla or similar",
    carType: "Compact",
    image:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop",
    transmission: "Automatic",
    seats: 5,
    luggage: 2,
    features: [
      { id: "1", name: "Unlimited mileage", icon: "unlimited" },
      { id: "2", name: "Free cancellation", icon: "cancel" },
      { id: "3", name: "Basic Collision Damage Protection", icon: "shield" },
      { id: "4", name: "Shuttle service", icon: "shuttle" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.4,
    reviewCount: 278,
    pricePerDay: 11.67,
    totalPrice: 35,
    currency: "$",
    company: "Compact",
    companyLogo: "https://via.placeholder.com/80x80/0066B2/FFFFFF?text=TOYOTA",
    isAvailable: true,
  },
  {
    id: "6",
    name: "Toyota Corolla or similar",
    carType: "Compact",
    image:
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&h=600&fit=crop",
    transmission: "Automatic",
    seats: 5,
    luggage: 2,
    features: [
      { id: "1", name: "Unlimited mileage", icon: "unlimited" },
      { id: "2", name: "Free cancellation", icon: "cancel" },
      { id: "3", name: "Basic Collision Damage Protection", icon: "shield" },
      { id: "4", name: "Excellent Coverage", icon: "coverage" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.8,
    reviewCount: 421,
    pricePerDay: 11.67,
    totalPrice: 35,
    currency: "$",
    company: "Compact",
    companyLogo: "https://via.placeholder.com/80x80/0066B2/FFFFFF?text=TOYOTA",
    isAvailable: true,
  },
  {
    id: "7",
    name: "Honda Civic",
    carType: "Economy",
    image:
      "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=600&fit=crop",
    transmission: "Manual",
    seats: 5,
    luggage: 2,
    features: [
      { id: "1", name: "Unlimited mileage", icon: "unlimited" },
      { id: "2", name: "Free cancellation", icon: "cancel" },
      { id: "3", name: "Air Conditioning", icon: "ac" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.2,
    reviewCount: 145,
    pricePerDay: 10,
    totalPrice: 30,
    currency: "$",
    company: "Budget",
    companyLogo: "https://via.placeholder.com/80x80/FF6B00/FFFFFF?text=BUDGET",
    isAvailable: true,
  },
  {
    id: "8",
    name: "BMW X5",
    carType: "SUV",
    image:
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&h=600&fit=crop",
    transmission: "Automatic",
    seats: 7,
    luggage: 5,
    features: [
      { id: "1", name: "Premium Sound", icon: "sound" },
      { id: "2", name: "Leather Seats", icon: "seat" },
      { id: "3", name: "Sunroof", icon: "sunroof" },
      { id: "4", name: "4WD", icon: "4wd" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.9,
    reviewCount: 203,
    pricePerDay: 40,
    totalPrice: 120,
    currency: "$",
    company: "Luxury Cars",
    companyLogo: "https://via.placeholder.com/80x80/0066B2/FFFFFF?text=BMW",
    isAvailable: true,
  },
  {
    id: "9",
    name: "Mercedes-Benz S-Class",
    carType: "Luxury",
    image:
      "https://images.unsplash.com/photo-1563720360172-67b8f3dce741?w=800&h=600&fit=crop",
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    features: [
      { id: "1", name: "Premium Sound", icon: "sound" },
      { id: "2", name: "Massage Seats", icon: "massage" },
      { id: "3", name: "Ambient Lighting", icon: "light" },
      { id: "4", name: "Advanced Safety", icon: "safety" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Limited (300km/day)",
    rating: 5.0,
    reviewCount: 89,
    pricePerDay: 62.67,
    totalPrice: 188,
    currency: "$",
    company: "Premium Rentals",
    companyLogo: "https://via.placeholder.com/80x80/00305C/FFFFFF?text=MB",
    isAvailable: true,
  },
  {
    id: "10",
    name: "Ford Transit Van",
    carType: "Van",
    image:
      "https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800&h=600&fit=crop",
    transmission: "Automatic",
    seats: 9,
    luggage: 8,
    features: [
      { id: "1", name: "Unlimited mileage", icon: "unlimited" },
      { id: "2", name: "GPS Navigation", icon: "gps" },
      { id: "3", name: "Air Conditioning", icon: "ac" },
      { id: "4", name: "Bluetooth", icon: "bluetooth" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.5,
    reviewCount: 167,
    pricePerDay: 25.67,
    totalPrice: 77,
    currency: "$",
    company: "Van Rentals",
    companyLogo: "https://via.placeholder.com/80x80/003478/FFFFFF?text=FORD",
    isAvailable: true,
  },
  {
    id: "11",
    name: "Audi A4",
    carType: "Midsize",
    image:
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop",
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    features: [
      { id: "1", name: "Unlimited mileage", icon: "unlimited" },
      { id: "2", name: "Premium Interior", icon: "premium" },
      { id: "3", name: "Advanced Safety", icon: "safety" },
      { id: "4", name: "Free cancellation", icon: "cancel" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.7,
    reviewCount: 192,
    pricePerDay: 13,
    totalPrice: 39,
    currency: "$",
    company: "Audi Rental",
    companyLogo: "https://via.placeholder.com/80x80/BB0A30/FFFFFF?text=AUDI",
    isAvailable: true,
  },
  {
    id: "12",
    name: "Hyundai Tucson",
    carType: "SUV",
    image:
      "https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=800&h=600&fit=crop",
    transmission: "Automatic",
    seats: 5,
    luggage: 4,
    features: [
      { id: "1", name: "Unlimited mileage", icon: "unlimited" },
      { id: "2", name: "Backup Camera", icon: "camera" },
      { id: "3", name: "Bluetooth", icon: "bluetooth" },
      { id: "4", name: "Free cancellation", icon: "cancel" },
    ],
    fuelPolicy: "Full to Full",
    mileage: "Unlimited",
    rating: 4.4,
    reviewCount: 221,
    pricePerDay: 13.33,
    totalPrice: 40,
    currency: "$",
    company: "Dollar",
    companyLogo: "https://via.placeholder.com/80x80/00A651/FFFFFF?text=DOLLAR",
    isAvailable: true,
  },
];
