import type { Tour } from "../Types/Tour/Tour.types";

export const SAMPLE_TOURS: Tour[] = [
  {
    id: "1",
    title: "Old Dhaka Heritage Walk",
    description: "Explore 400 years of history",
    location: "Dhaka, Bangladesh",
    city: "Dhaka",
    country: "Bangladesh",
    category: "Cultural",
    image:
      "https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=800&h=600&fit=crop",
    price: 2500,
    currency: "BDT",
    rating: 4.7,
    reviewCount: 391,
    duration: { days: 1, nights: 0 },
    features: ["Guide", "Food", "Transport"],
  },
  {
    id: "2",
    title: "Cox's Bazar Beach Paradise",
    description: "Relax on the world's longest beach",
    location: "Cox's Bazar, Bangladesh",
    city: "Cox's Bazar",
    country: "Bangladesh",
    category: "Beach",
    image:
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop",
    price: 8500,
    currency: "BDT",
    rating: 4.6,
    reviewCount: 243,
    duration: { days: 2, nights: 1 },
    features: ["Hotel", "Meals", "Beach Access"],
  },
  {
    id: "3",
    title: "Bandarban Hill Tracts Expedition",
    description: "Adventure in the hills",
    location: "Bandarban, Bangladesh",
    city: "Bandarban",
    country: "Bangladesh",
    category: "Hill Tracts",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
    price: 11500,
    currency: "BDT",
    rating: 4.8,
    reviewCount: 243,
    duration: { days: 4, nights: 3 },
    features: ["Trekking", "Local Guide", "Camping"],
  },
  {
    id: "4",
    title: "Sylhet Tea Garden Retreat",
    description: "Discover tea gardens and natural wonders",
    location: "Sylhet, Bangladesh",
    city: "Sylhet",
    country: "Bangladesh",
    category: "Nature",
    image:
      "https://images.unsplash.com/photo-1563207153-f403bf289096?w=800&h=600&fit=crop",
    price: 9800,
    currency: "BDT",
    rating: 4.8,
    reviewCount: 391,
    duration: { days: 3, nights: 2 },
    features: ["Tea Estate", "Waterfall", "Boat Ride"],
  },
  {
    id: "5",
    title: "Sundarbans Mangrove Adventure",
    description: "Experience the wild beauty of Sundarbans",
    location: "Khulna, Bangladesh",
    city: "Khulna",
    country: "Bangladesh",
    category: "Wildlife",
    image:
      "https://images.unsplash.com/photo-1535083783855-76ae62b2914e?w=800&h=600&fit=crop",
    price: 12500,
    currency: "BDT",
    rating: 4.9,
    reviewCount: 321,
    duration: { days: 3, nights: 2 },
    features: ["Wildlife Safari", "Boat Tour", "Expert Guide"],
  },
  {
    id: "6",
    title: "Ancient Buddhist Vihara Discovery",
    description: "Ancient Buddhist heritage",
    location: "Naogaon, Bangladesh",
    city: "Naogaon",
    country: "Bangladesh",
    category: "Religious",
    image:
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&h=600&fit=crop",
    price: 4500,
    currency: "BDT",
    rating: 4.9,
    reviewCount: 321,
    duration: { days: 3, nights: 2 },
    features: ["Historical Sites", "Guide", "Museum"],
  },
  {
    id: "7",
    title: "Rangamati Lake Adventure",
    description: "Explore crystal blue lakes and tribal culture",
    location: "Rangamati, Bangladesh",
    city: "Rangamati",
    country: "Bangladesh",
    category: "Adventure",
    image:
      "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&h=600&fit=crop",
    price: 7500,
    currency: "BDT",
    rating: 4.7,
    reviewCount: 187,
    duration: { days: 2, nights: 1 },
    features: ["Boat Ride", "Tribal Village", "Lake View"],
  },
  {
    id: "8",
    title: "Srimangal Tea Capital Tour",
    description: "Seven-layer tea and lush green gardens",
    location: "Srimangal, Bangladesh",
    city: "Srimangal",
    country: "Bangladesh",
    category: "Nature",
    image:
      "https://images.unsplash.com/photo-1564516344729-5e3e2b7b2e3f?w=800&h=600&fit=crop",
    price: 6800,
    currency: "BDT",
    rating: 4.6,
    reviewCount: 156,
    duration: { days: 2, nights: 1 },
    features: ["Tea Tasting", "Nature Walk", "Bird Watching"],
  },
  {
    id: "9",
    title: "Saint Martin Island Escape",
    description: "Bangladesh's only coral island",
    location: "Saint Martin, Bangladesh",
    city: "Saint Martin",
    country: "Bangladesh",
    category: "Beach",
    image:
      "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800&h=600&fit=crop",
    price: 15000,
    currency: "BDT",
    rating: 4.9,
    reviewCount: 412,
    duration: { days: 3, nights: 2 },
    features: ["Coral Reef", "Beach Resort", "Seafood"],
  },
  {
    id: "10",
    title: "Paharpur Buddhist Monastery",
    description: "UNESCO World Heritage archaeological site",
    location: "Naogaon, Bangladesh",
    city: "Naogaon",
    country: "Bangladesh",
    category: "Cultural",
    image:
      "https://images.unsplash.com/photo-1512581192389-49c0f7a0d5a7?w=800&h=600&fit=crop",
    price: 3500,
    currency: "BDT",
    rating: 4.5,
    reviewCount: 98,
    duration: { days: 1, nights: 0 },
    features: ["UNESCO Site", "Archaeology", "Photography"],
  },
  {
    id: "11",
    title: "Chittagong Hill Tracts Explorer",
    description: "Discover tribal culture and mountain beauty",
    location: "Chittagong, Bangladesh",
    city: "Chittagong",
    country: "Bangladesh",
    category: "Hill Tracts",
    image:
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop",
    price: 10500,
    currency: "BDT",
    rating: 4.7,
    reviewCount: 234,
    duration: { days: 4, nights: 3 },
    features: ["Tribal Culture", "Mountain Trek", "Local Food"],
  },
  {
    id: "12",
    title: "Kuakata Sea Beach Retreat",
    description: "Watch both sunrise and sunset",
    location: "Patuakhali, Bangladesh",
    city: "Patuakhali",
    country: "Bangladesh",
    category: "Beach",
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop",
    price: 7200,
    currency: "BDT",
    rating: 4.5,
    reviewCount: 176,
    duration: { days: 2, nights: 1 },
    features: ["Sunrise", "Sunset", "Beach Activities"],
  },
  {
    id: "13",
    title: "Ratargul Swamp Forest Tour",
    description: "Bangladesh's only swamp forest",
    location: "Sylhet, Bangladesh",
    city: "Sylhet",
    country: "Bangladesh",
    category: "Nature",
    image:
      "https://images.unsplash.com/photo-1511497584788-876760111969?w=800&h=600&fit=crop",
    price: 5500,
    currency: "BDT",
    rating: 4.6,
    reviewCount: 203,
    duration: { days: 1, nights: 0 },
    features: ["Boat Ride", "Wildlife", "Photography"],
  },
  {
    id: "14",
    title: "Dhaka City Tours Package",
    description: "Explore the vibrant capital city",
    location: "Dhaka, Bangladesh",
    city: "Dhaka",
    country: "Bangladesh",
    category: "City Tours",
    image:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop",
    price: 3200,
    currency: "BDT",
    rating: 4.4,
    reviewCount: 289,
    duration: { days: 1, nights: 0 },
    features: ["City Tour", "Food Tasting", "Shopping"],
  },
  {
    id: "15",
    title: "Nijhum Dwip Wildlife Sanctuary",
    description: "Remote island with spotted deer",
    location: "Noakhali, Bangladesh",
    city: "Noakhali",
    country: "Bangladesh",
    category: "Wildlife",
    image:
      "https://images.unsplash.com/photo-1503435980610-a51f3ddfee50?w=800&h=600&fit=crop",
    price: 8900,
    currency: "BDT",
    rating: 4.7,
    reviewCount: 145,
    duration: { days: 2, nights: 1 },
    features: ["Wildlife Spotting", "Island Stay", "Nature Walk"],
  },
  {
    id: "16",
    title: "Sajek Valley Paradise",
    description: "Queen of hills with cloud views",
    location: "Rangamati, Bangladesh",
    city: "Rangamati",
    country: "Bangladesh",
    category: "Hill Tracts",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
    price: 13500,
    currency: "BDT",
    rating: 4.9,
    reviewCount: 387,
    duration: { days: 3, nights: 2 },
    features: ["Mountain View", "Cloud Experience", "Tribal Culture"],
  },
  {
    id: "17",
    title: "Boga Lake Trek",
    description: "Adventurous trek to mountain lake",
    location: "Bandarban, Bangladesh",
    city: "Bandarban",
    country: "Bangladesh",
    category: "Adventure",
    image:
      "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=800&h=600&fit=crop",
    price: 9500,
    currency: "BDT",
    rating: 4.8,
    reviewCount: 167,
    duration: { days: 2, nights: 1 },
    features: ["Trekking", "Mountain Lake", "Camping"],
  },
  {
    id: "18",
    title: "Mahasthangarh Ancient City",
    description: "Oldest archaeological site in Bangladesh",
    location: "Bogra, Bangladesh",
    city: "Bogra",
    country: "Bangladesh",
    category: "Cultural",
    image:
      "https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?w=800&h=600&fit=crop",
    price: 4200,
    currency: "BDT",
    rating: 4.5,
    reviewCount: 124,
    duration: { days: 1, nights: 0 },
    features: ["Ancient Ruins", "Museum", "History Tour"],
  },
];