import type {
  FlightBooking,
  HotelBooking,
  TripBooking,
} from "../Types/Booking/MyBooking.types";

// ===============================Flight Bookings==============================

export const SAMPLE_FLIGHT_BOOKINGS: FlightBooking[] = [
  {
    id: "FL001",
    type: "flight",
    bookingReference: "JL787-TKY2026",
    airline: "Japan Airlines",
    flightNumber: "JL 787",
    departureCity: "New York",
    departureCode: "NYC",
    arrivalCity: "Tokyo",
    arrivalCode: "TYO",
    departureTime: "10:20 AM",
    arrivalTime: "3:45 PM",
    departureDate: "5-8 Jun 2026",
    arrivalDate: "6-8 Jun 2026",
    duration: "14h 15m",
    class: "Business",
    passengers: 3,
    totalPrice: 3450,
    currency: "$",
    status: "confirmed",
    bookingDate: "2026-01-10",
  },
  {
    id: "FL002",
    type: "flight",
    bookingReference: "BA123-LHR2026",
    airline: "British Airways",
    flightNumber: "BA 123",
    departureCity: "New York",
    departureCode: "JFK",
    arrivalCity: "London",
    arrivalCode: "LHR",
    departureTime: "8:00 PM",
    arrivalTime: "8:15 AM",
    departureDate: "15 Feb 2026",
    arrivalDate: "16 Feb 2026",
    duration: "7h 15m",
    class: "Economy",
    passengers: 2,
    totalPrice: 1850,
    currency: "$",
    status: "pending",
    bookingDate: "2026-01-12",
  },
];

// ===============================Hotel Bookings==============================

export const SAMPLE_HOTEL_BOOKINGS: HotelBooking[] = [
  {
    id: "HT001",
    type: "hotel",
    bookingReference: "GPH-DXB2026",
    hotelName: "Grand Plaza Hotel",
    rating: 4.5,
    location: "Downtown Dubai",
    city: "Dubai",
    country: "UAE",
    amenities: [
      { icon: "pool", label: "Pool" },
      { icon: "restaurant", label: "3 Restaurant" },
      { icon: "wifi", label: "Free Wifi" },
      { icon: "parking", label: "3 Parking" },
      { icon: "gym", label: "3 GYM" },
      { icon: "ac", label: "3 AC" },
    ],
    checkIn: "2:00 PM",
    checkOut: "12:00 PM",
    checkInTime: "2:00 PM",
    checkOutTime: "12:00 PM",
    roomType: "Deluxe Suite",
    guests: 2,
    view: "City View",
    parking: 3,
    totalPrice: 180,
    pricePerNight: 180,
    currency: "$",
    status: "confirmed",
    bookingDate: "2026-01-08",
  },
  {
    id: "HT002",
    type: "hotel",
    bookingReference: "MRH-PAR2026",
    hotelName: "Majestic Royal Hotel",
    rating: 5.0,
    location: "Champs-Élysées",
    city: "Paris",
    country: "France",
    amenities: [
      { icon: "pool", label: "Pool" },
      { icon: "restaurant", label: "5 Restaurant" },
      { icon: "wifi", label: "Free Wifi" },
      { icon: "parking", label: "Valet Parking" },
      { icon: "spa", label: "Spa" },
      { icon: "gym", label: "Gym" },
    ],
    checkIn: "3:00 PM",
    checkOut: "11:00 AM",
    checkInTime: "3:00 PM",
    checkOutTime: "11:00 AM",
    roomType: "Presidential Suite",
    guests: 2,
    view: "Eiffel Tower View",
    parking: 1,
    totalPrice: 450,
    pricePerNight: 450,
    currency: "$",
    status: "confirmed",
    bookingDate: "2026-01-09",
  },
];

// ===============================Trip Bookings==============================

export const SAMPLE_TRIP_BOOKINGS: TripBooking[] = [
  {
    id: "TR001",
    type: "trip",
    bookingReference: "ZR-ABJ2026",
    tripName: "Zuma Rock",
    rating: 4.5,
    location: "Abuja",
    city: "Abuja",
    country: "Nigeria",
    inclusions: [
      { icon: "hotel", label: "Hotel Stay" },
      { icon: "meal", label: "All Meals" },
      { icon: "transport", label: "Transport" },
      { icon: "guide", label: "Tour Guide" },
      { icon: "insurance", label: "Insurance" },
    ],
    duration: 5,
    groupSize: "2-10 People",
    startDate: "Feb 16, 2026",
    endDate: "Feb 20, 2026",
    totalPrice: 899,
    pricePerPerson: 899,
    currency: "$",
    status: "confirmed",
    bookingDate: "2026-01-11",
  },
  {
    id: "TR002",
    type: "trip",
    bookingReference: "OSG-ONO2026",
    tripName: "Osun-Osogbo Sacred Grove",
    rating: 4.8,
    location: "Osogbo",
    city: "Osogbo",
    country: "Nigeria",
    inclusions: [
      { icon: "hotel", label: "Hotel Stay" },
      { icon: "meal", label: "All Meals" },
      { icon: "transport", label: "Transport" },
      { icon: "guide", label: "Tour Guide" },
      { icon: "insurance", label: "Insurance" },
    ],
    duration: 5,
    groupSize: "5-15 People",
    startDate: "Feb 20, 2026",
    endDate: "Feb 24, 2026",
    totalPrice: 899,
    pricePerPerson: 899,
    currency: "$",
    status: "confirmed",
    bookingDate: "2026-01-11",
  },
  {
    id: "TR003",
    type: "trip",
    bookingReference: "YGR-KAN2026",
    tripName: "Yankari Game Reserve",
    rating: 4.6,
    location: "Bauchi",
    city: "Kano",
    country: "Nigeria",
    inclusions: [
      { icon: "hotel", label: "Hotel Stay" },
      { icon: "meal", label: "All Meals" },
      { icon: "transport", label: "Transport" },
      { icon: "guide", label: "Tour Guide" },
      { icon: "insurance", label: "Insurance" },
    ],
    duration: 4,
    groupSize: "4-12 People",
    startDate: "Mar 1, 2026",
    endDate: "Mar 4, 2026",
    totalPrice: 1299,
    pricePerPerson: 1299,
    currency: "$",
    status: "pending",
    bookingDate: "2026-01-13",
  },
];
