import { Hotel } from "@/Types/Hotel/hotel";

export const mockHotels: Hotel[] = [
  {
    id: 1,
    name: "The Fullerton Hotel Singapore",
    image: "https://picsum.photos/seed/hotel1/800/600",
    rating: 5.0,
    reviews: 11200,
    description:
      "5-star hotel located in Singapore. Close to Chinatown Heritage Center and Universal Studios Singapore...",
    location: "Fullerton Square",
    price: 2024,
    starRating: 5,
    amenities: ["Pool", "Spa", "Restaurant", "Gym", "Bar", "Air conditioned"],
    accessibility: ["Lift", "Wheelchair-accessible parking"],
    mealPlans: ["Breakfast included", "Full board"],
    propertyType: "Hotel",
    travelerExperience: ["Luxury", "Romantic"],
  },
  {
    id: 2,
    name: "Rosewood Mayakoba",
    image: "https://picsum.photos/seed/hotel2/800/600",
    rating: 4.5,
    reviews: 1200,
    description:
      "Luxury beachfront resort with stunning ocean views and world-class amenities.",
    location: "Mayakoba",
    price: 1850,
    starRating: 5,
    amenities: ["Pool", "Spa", "Restaurant", "Hot tub", "Bar"],
    accessibility: ["Lift", "Accessible bathroom"],
    mealPlans: ["All-inclusive"],
    propertyType: "Hotel",
    travelerExperience: ["Luxury", "Romantic"],
  },
  {
    id: 3,
    name: "Hotel Emma",
    image: "https://picsum.photos/seed/hotel3/800/600",
    rating: 4.5,
    reviews: 1200,
    description:
      "Boutique hotel with modern design and exceptional service in the heart of the city.",
    location: "San Antonio",
    price: 1450,
    starRating: 4,
    amenities: ["Restaurant", "Bar", "Air conditioned", "Gym"],
    accessibility: ["Lift", "Stair-free path to entrance"],
    mealPlans: ["Breakfast included"],
    propertyType: "Hotel",
    travelerExperience: ["Romantic"],
  },
  {
    id: 4,
    name: "The Inn at Lost Creek",
    image: "https://picsum.photos/seed/hotel4/800/600",
    rating: 4.5,
    reviews: 1200,
    description:
      "Mountain retreat offering cozy accommodations and breathtaking alpine views.",
    location: "Lost Creek",
    price: 1200,
    starRating: 4,
    amenities: ["Pool", "Spa", "Restaurant", "Hot tub", "Gym"],
    accessibility: ["Lift"],
    mealPlans: ["Half board"],
    propertyType: "Bed & Breakfast",
    travelerExperience: ["Romantic"],
  },
  {
    id: 5,
    name: "Hotel Acta Azul Barcelona",
    image: "https://picsum.photos/seed/hotel5/800/600",
    rating: 4.5,
    reviews: 1200,
    description:
      "Contemporary hotel near Barcelona beach with rooftop pool and Mediterranean cuisine.",
    location: "Barcelona",
    price: 980,
    starRating: 3,
    amenities: ["Pool", "Restaurant", "Bar", "Air conditioned"],
    accessibility: ["Lift"],
    mealPlans: ["Breakfast included"],
    propertyType: "Hotel",
    travelerExperience: ["Budget"],
  },
  {
    id: 6,
    name: "Grand Palace Hotel",
    image: "https://picsum.photos/seed/hotel6/800/600",
    rating: 5.0,
    reviews: 2400,
    description:
      "Historic luxury hotel featuring opulent rooms and fine dining experiences.",
    location: "Paris",
    price: 2800,
    starRating: 5,
    amenities: ["Restaurant", "Bar", "Spa", "Gym", "Casino", "Air conditioned"],
    accessibility: [
      "Lift",
      "Wheelchair-accessible parking",
      "Accessible bathroom",
    ],
    mealPlans: ["Breakfast included", "Full board"],
    propertyType: "Hotel",
    travelerExperience: ["Luxury", "Romantic"],
  },
  {
    id: 7,
    name: "Seaside Resort & Spa",
    image: "https://picsum.photos/seed/hotel7/800/600",
    rating: 4.0,
    reviews: 1800,
    description:
      "Tropical paradise with private beach access and full-service spa.",
    location: "Maldives",
    price: 3200,
    starRating: 5,
    amenities: ["Pool", "Spa", "Restaurant", "Bar", "Gym", "Outdoor space"],
    accessibility: ["Wheelchair-accessible parking"],
    mealPlans: ["All-inclusive"],
    propertyType: "Hotel",
    travelerExperience: ["Luxury", "Romantic"],
  },
  {
    id: 8,
    name: "Urban Boutique Suites",
    image: "https://picsum.photos/seed/hotel8/800/600",
    rating: 4.5,
    reviews: 950,
    description:
      "Stylish suites in the business district with modern amenities.",
    location: "New York",
    price: 1650,
    starRating: 4,
    amenities: ["Gym", "Air conditioned", "Bar"],
    accessibility: ["Lift", "Accessible bathroom"],
    mealPlans: ["Breakfast included"],
    propertyType: "Aparthotel",
    travelerExperience: ["Adult only"],
  },
  {
    id: 9,
    name: "Mountain View Lodge",
    image: "https://picsum.photos/seed/hotel9/800/600",
    rating: 4.0,
    reviews: 1100,
    description:
      "Rustic lodge with panoramic mountain views and outdoor activities.",
    location: "Swiss Alps",
    price: 1380,
    starRating: 3,
    amenities: ["Restaurant", "Bar", "Outdoor space", "Hot tub"],
    accessibility: ["Stair-free path to entrance"],
    mealPlans: ["Half board"],
    propertyType: "Bed & Breakfast",
    travelerExperience: ["Budget"],
  },
  {
    id: 10,
    name: "City Center Plaza",
    image: "https://picsum.photos/seed/hotel10/800/600",
    rating: 4.5,
    reviews: 2100,
    description:
      "Modern hotel in prime location with easy access to shopping and dining.",
    location: "Tokyo",
    price: 1520,
    starRating: 4,
    amenities: ["Restaurant", "Gym", "Air conditioned", "Bar"],
    accessibility: ["Lift", "Wheelchair-accessible parking"],
    mealPlans: ["Breakfast included"],
    propertyType: "Hotel",
    travelerExperience: ["Budget"],
  },
  {
    id: 11,
    name: "Lakeside Retreat",
    image: "https://picsum.photos/seed/hotel11/800/600",
    rating: 4.0,
    reviews: 850,
    description:
      "Peaceful lakefront property perfect for relaxation and water activities.",
    location: "Lake Como",
    price: 1100,
    starRating: 3,
    amenities: ["Pool", "Restaurant", "Outdoor space", "Pet-friendly"],
    accessibility: ["Stair-free path to entrance", "Service animals allowed"],
    mealPlans: ["Breakfast included"],
    propertyType: "Bed & Breakfast",
    travelerExperience: ["Budget", "Romantic"],
  },
  {
    id: 12,
    name: "Desert Oasis Resort",
    image: "https://picsum.photos/seed/hotel12/800/600",
    rating: 4.5,
    reviews: 1350,
    description:
      "Luxurious desert resort with infinity pool and stunning sunset views.",
    location: "Dubai",
    price: 2450,
    starRating: 5,
    amenities: ["Pool", "Spa", "Restaurant", "Bar", "Gym", "Golf"],
    accessibility: [
      "Lift",
      "Wheelchair-accessible parking",
      "Accessible bathroom",
    ],
    mealPlans: ["All-inclusive"],
    propertyType: "Hotel",
    travelerExperience: ["Luxury"],
  },
  {
    id: 13,
    name: "Historic Castle Inn",
    image: "https://picsum.photos/seed/hotel13/800/600",
    rating: 5.0,
    reviews: 1650,
    description:
      "Experience medieval charm in this restored castle with modern comforts.",
    location: "Scotland",
    price: 1980,
    starRating: 5,
    amenities: ["Restaurant", "Bar", "Spa"],
    accessibility: ["Service animals allowed"],
    mealPlans: ["Breakfast included", "Full board"],
    propertyType: "Hotel",
    travelerExperience: ["Luxury", "Romantic"],
  },
  {
    id: 14,
    name: "Tropical Garden Hotel",
    image: "https://picsum.photos/seed/hotel14/800/600",
    rating: 4.0,
    reviews: 1420,
    description:
      "Lush tropical gardens surround this serene hotel with spa facilities.",
    location: "Bali",
    price: 890,
    starRating: 3,
    amenities: ["Pool", "Spa", "Restaurant", "Outdoor space"],
    accessibility: ["Stair-free path to entrance"],
    mealPlans: ["Breakfast included"],
    propertyType: "Hotel",
    travelerExperience: ["Budget"],
  },
  {
    id: 15,
    name: "Metropolitan Tower",
    image: "https://picsum.photos/seed/hotel15/800/600",
    rating: 4.5,
    reviews: 1750,
    description: "High-rise hotel with skyline views and rooftop restaurant.",
    location: "London",
    price: 1820,
    starRating: 4,
    amenities: ["Restaurant", "Bar", "Gym", "Air conditioned"],
    accessibility: ["Lift", "Accessible bathroom"],
    mealPlans: ["Breakfast included"],
    propertyType: "Hotel",
    travelerExperience: ["Adult only"],
  },
];
